@startuml

package "The Creator classes" {
  class PizzaStore

  class NYPizzaStore extends PizzaStore
  class ChicagoPizzaStore extends PizzaStore
}

package "The Product classes" {
  class Pizza

  class NYStyleCheesePizza extends Pizza
  class NYStyleClamPizza extends Pizza

  class ChicagoStyleCheesePizza extends Pizza
  class ChicagoStyleClamPizza extends Pizza

}


note "<b>Abstract</b> Factory produces <b>Abstract</b> Product." as N1
PizzaStore .. N1
N1 .. Pizza

note "<b>Concrete</b> Factory produces <b>Concrete</b> Product." as N2
NYPizzaStore .. N2
N2 .. NYStyleClamPizza
@enduml
