@startuml

abstract class Beverage {
  description
  getDescription()
  cost()
}

class HouseBlend extends Beverage {
  cost()
}

class DarkRoast extends Beverage {
  cost()
}

class Decaf extends Beverage {
  cost()
}

class Espresso extends Beverage {
  cost()
}


class EspressoWithMilk extends Beverage {
  cost()
}

class EspressoWithSoy extends Beverage {
  cost()
}

class EspressoWithWhip extends Beverage {
  cost()
}

@enduml