@startuml

interface Iterator {
 hasNext()
 next()
 remove()
}

class ConcreteIterator implements Iterator{
 hasNext()
 next()
 remove()
}

interface Aggregate {
  createIterator()
}

class ConcreteAggregate implements Aggregate{
  createIterator()
}

Client -left--> Aggregate : has_one
Client -right-> Iterator : use
@enduml
