@startuml
scale 350 width
[*] --> NoQuarter


HasQuarter --> NoQuarter  : eject quarter
HasQuarter --> GumballSold : turns crank
NoQuarter  --> HasQuarter : insert quarter
GumballSold --> NoQuarter : dispense gumball and gumballs > 0
GumballSold --> OutOfGumballs : dispense gumball and gumballs = 0
@enduml
